'use client';
import {ListingHistory} from '@/app/(main)/admin/_components/record-history';
import {useState} from 'react';
import {useListIlanlarAdminQuery,useUpdateIlanStatusAdminMutation,useDeleteIlanAdminMutation} from '@/integrations/hooks';
import {formatIlanPurchaseDate,type IlanAdminItem,type IlanStatus} from '@/integrations/shared';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const labels:Record<IlanStatus,string>={active:'Yayında',pending_approval:'İncelemede',paused:'Duraklatıldı',sold:'Satıldı',expired:'Süresi doldu',cancelled:'İptal',removed:'Arşivlendi'};
export default function AdminIlanlarClient(){
 const [page,setPage]=useState(1),[status,setStatus]=useState(''),[city,setCity]=useState(''),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[selected,setSelected]=useState<IlanAdminItem|null>(null);
 const list=useListIlanlarAdminQuery({page,status:status||undefined,from_city:query||undefined});const [update,{isLoading:updating}]=useUpdateIlanStatusAdminMutation(),[archive,{isLoading:archiving}]=useDeleteIlanAdminMutation();
 async function change(ilan:IlanAdminItem,next:IlanStatus){try{await update({id:ilan.id,status:next}).unwrap();setMessage('İlan durumu güncellendi.');list.refetch();}catch{setMessage('Durum değiştirilemedi. Satılmış, geçmiş veya ödeme bekleyen ilanlar yeniden yayımlanamaz.');}}
 return <Card><CardHeader><CardTitle>İlan yönetimi</CardTitle><CardDescription>Rota ilanlarını inceleyin, yayın durumunu yönetin. İletişim satışı taşıma ücreti değildir.</CardDescription></CardHeader><CardContent className="space-y-5">
 <form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(city);}}><label htmlFor="listing-city" className="text-sm">Kalkış şehri<Input id="listing-city" value={city} onChange={e=>setCity(e.target.value)}/></label><label className="text-sm">Durum<select className="block h-10 rounded-md border bg-background px-3" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tümü</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><Button variant="outline">Filtrele</Button><Button type="button" variant="outline" onClick={()=>list.refetch()}>Yenile</Button></form>
 <output className="text-sm">{message}</output>{list.isError?<p role="alert">İlanlar yüklenemedi. Yenileyerek tekrar deneyin.</p>:list.isLoading?<output>Yükleniyor…</output>:<div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Rota / ilan sahibi</TableHead><TableHead>Hareket</TableHead><TableHead>Araç</TableHead><TableHead>Durum</TableHead><TableHead>İşlemler</TableHead></TableRow></TableHeader><TableBody>{list.data?.data.map(ilan=><TableRow key={ilan.id}><TableCell><p className="font-medium">{ilan.from_city} → {ilan.to_city}</p><p className="text-sm text-muted-foreground">{ilan.carrier_name||'İlan sahibi'}</p></TableCell><TableCell>{formatIlanPurchaseDate(ilan.departure_date)}</TableCell><TableCell>{({car:'Otomobil',van:'Kamyonet',truck:'Kamyon',motorcycle:'Motosiklet',other:'Diğer'})[ilan.vehicle_type]}</TableCell><TableCell>{labels[ilan.status]??ilan.status}</TableCell><TableCell><div className="flex gap-2"><Button variant="outline" onClick={()=>setSelected(ilan)}>Detay</Button>{!['sold','removed','expired'].includes(ilan.status)&&<><Button variant="outline" disabled={updating||ilan.status==='active'} onClick={()=>change(ilan,'active')}>Yayımla</Button><Button variant="outline" disabled={updating||ilan.status==='paused'} onClick={()=>change(ilan,'paused')}>Duraklat</Button><Button variant="outline" disabled={archiving} onClick={async()=>{if(!window.confirm('İlan arşivlensin mi?'))return;try{await archive({id:ilan.id}).unwrap();setMessage('İlan arşivlendi.');list.refetch();}catch{setMessage('Arşivlenemedi. Ödeme durumunu kontrol edin.');}}}>Arşivle</Button></>}</div></TableCell></TableRow>)}{!list.data?.data.length&&<TableRow><TableCell colSpan={5} className="py-10 text-center">Bu filtrede ilan bulunmuyor.</TableCell></TableRow>}</TableBody></Table></div>}
 <div className="flex items-center justify-between"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Önceki</Button><span className="text-sm">{list.data?.total??'—'} ilan · Sayfa {page}</span><Button variant="outline" disabled={page*(list.data?.limit??20)>=(list.data?.total??0)} onClick={()=>setPage(p=>p+1)}>Sonraki</Button></div>
 {selected&&<Dialog open onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{selected.from_city} → {selected.to_city}</DialogTitle><DialogDescription>{selected.id}</DialogDescription></DialogHeader><p>{selected.title}</p><p className="whitespace-pre-wrap break-words">{selected.description}</p><p>{selected.contact_phone}</p><p className="text-sm">{labels[selected.status]} · {formatIlanPurchaseDate(selected.departure_date)}</p><p className="text-sm text-muted-foreground">Satın alma kaydı ve alıcısı İletişim satışları ekranında; durum değişiklikleri denetim kaydında saklanır.</p><ListingHistory id={selected.id}/></DialogContent></Dialog>}
 </CardContent></Card>;
}
