import { db } from "@/db/client";
import { desc, eq, sql } from "drizzle-orm";
import { users } from "@/modules/auth";
import { userRoles } from "@/modules/userRoles";
import { ilanlar } from "@/modules/ilanlar";
import { bookings } from "@/modules/bookings";
import { wallets, walletTransactions } from "@/modules/wallet";
import { ratings } from "@/modules/ratings";
import { buildCarriersWhere, type CarriersListParams } from "./helpers";
export type CarrierListItem = {
  id: string;
  email: string;
  full_name: string | null;
  phone: string | null;
  is_active: boolean;
  email_verified: boolean;
  created_at: Date | string;
  last_sign_in_at: Date | string | null;
  ilan_count: number;
  active_ilan_count: number;
  booking_count: number;
  delivered_booking_count: number;
  rating_avg: number;
  rating_count: number;
  wallet_balance: string;
  wallet_status: string | null;
};
export type CarrierDetailIlan = {
  id: string;
  from_city: string;
  to_city: string;
  departure_date: Date | string;
  status: string;
  available_capacity_kg: string;
  price_per_kg: string;
  currency: string;
  created_at: Date | string;
};
export type CarrierDetailBooking = {
  id: string;
  customer_id: string;
  status: string;
  payment_status: string;
  kg_amount: string;
  total_price: string;
  currency: string;
  created_at: Date | string;
  delivered_at: Date | string | null;
};
export type CarrierDetailRating = {
  id: string;
  customer_id: string;
  score: number;
  comment: string | null;
  created_at: Date | string;
};
export type CarrierDetailStats = {
  ilan_count: number;
  active_ilan_count: number;
  booking_count: number;
  delivered_booking_count: number;
  rating_avg: number;
  rating_count: number;
  wallet_balance: string;
  wallet_status: string | null;
  wallet_total_earnings: string;
  wallet_total_withdrawn: string;
  total_transaction_count: number;
};
export type CarrierDetail = {
  id: string;
  email: string;
  full_name: string | null;
  phone: string | null;
  is_active: boolean;
  email_verified: boolean;
  created_at: Date | string;
  last_sign_in_at: Date | string | null;
  stats: CarrierDetailStats;
  recent_ilanlar: CarrierDetailIlan[];
  recent_bookings: CarrierDetailBooking[];
  recent_ratings: CarrierDetailRating[];
};
