import { afterAll, describe, expect, it } from 'bun:test';
import { eq } from 'drizzle-orm';
import { db } from '@/db/client';
import { ilanlar } from '@/modules/ilanlar/schema';
import { paymentSessions } from '@/modules/purchases/session.schema';
import { creditLedger, ilanPurchases } from '@/modules/purchases/schema';
import { repoGetCreditBalance, repoGetCreditPackages, repoGrantCredits, repoPurchaseIlan } from '@/modules/purchases/repository';
import { repoCreateIlanPayment, repoCompleteIlanPayment, repoCreateCreditPackagePayment, repoCompleteCreditPackagePayment, repoFailCreditPackagePayment } from '@/modules/purchases/payment.repository';
import { repoMyPayment } from '@/modules/purchases/session.repository';
import { buyer, declaration, listing } from './purchase-fixtures';
import { closeTestApp } from './setup';
afterAll(closeTestApp);
const proof = (amount: number, paymentId: string) => ({provider: 'shopier', amount, currency: 'TRY', paymentId});

describe('Contact purchase integrity with real MySQL locks', () => {
  it('two credit buyers each get access and each spend one right; replay is free', async () => {
    const owner = await buyer(), a = await buyer(), b = await buyer();
    const id = await listing(owner.id);
    await Promise.all([repoGrantCredits(a.id, 2, 'admin_grant'), repoGrantCredits(b.id, 2, 'admin_grant')]);
    const results = await Promise.all([repoPurchaseIlan(id, a.id, declaration, '127.0.0.1'), repoPurchaseIlan(id, b.id, declaration, '127.0.0.1')]);
    expect(results.filter(x => x.ok)).toHaveLength(2);
    const again = await repoPurchaseIlan(id, a.id, declaration, '127.0.0.1');
    expect(again.ok).toBe(true);
    expect(await repoGetCreditBalance(a.id)).toBe(1);
    expect(await repoGetCreditBalance(b.id)).toBe(1);
    expect((await db.select().from(ilanlar).where(eq(ilanlar.id,id)))[0]?.status).toBe('active');
    expect(await db.select().from(ilanPurchases).where(eq(ilanPurchases.ilan_id,id))).toHaveLength(2);
  });
  it('card reservations are per buyer; another buyer may spend a right', async () => {
    const owner = await buyer(), a = await buyer(), b = await buyer();
    const id = await listing(owner.id);
    await repoGrantCredits(b.id, 2, 'admin_grant');
    const results = await Promise.all([repoCreateIlanPayment(id,a.id,'shopier',declaration,'127.0.0.1'),repoCreateIlanPayment(id,b.id,'shopier',declaration,'127.0.0.1')]);
    expect(results.filter(x => x.ok)).toHaveLength(2);
    const [first,second]=results;
    if (!first.ok || !second.ok) throw new Error('fixture');
    expect((await repoPurchaseIlan(id,a.id,declaration,'127.0.0.1')).ok).toBe(false);
    expect((await repoPurchaseIlan(id,b.id,declaration,'127.0.0.1')).ok).toBe(false);
    const other=await buyer();
    await repoGrantCredits(other.id,1,'admin_grant');
    expect((await repoPurchaseIlan(id,other.id,declaration,'127.0.0.1')).ok).toBe(true);
    const ref = first.payment.payment_ref;
    expect((await repoCompleteIlanPayment(ref,proof(first.price+1,ref))).ok).toBe(false);
    expect((await repoCompleteIlanPayment(ref,{...proof(first.price,ref),currency:'USD'})).ok).toBe(false);
    const callbacks = await Promise.all([repoCompleteIlanPayment(ref,proof(first.price,ref)),repoCompleteIlanPayment(ref,proof(first.price,ref))]);
    expect(callbacks.every(x=>x.ok)).toBe(true);
    expect((await repoCompleteIlanPayment(second.payment.payment_ref,proof(second.price,second.payment.payment_ref))).ok).toBe(true);
    expect(await db.select().from(ilanPurchases).where(eq(ilanPurchases.ilan_id,id))).toHaveLength(3);
    expect((await repoCreateIlanPayment(id,a.id,'shopier',declaration,'127.0.0.1')).ok).toBe(false);
    expect(await repoMyPayment(ref,owner.id)).toBeUndefined();
  });
  it('late captured payment is recorded for refund and does not deliver', async () => {
    const owner = await buyer(), a = await buyer();
    const id = await listing(owner.id);
    const payment = await repoCreateIlanPayment(id,a.id,'shopier',declaration,'127.0.0.1');
    if (!payment.ok) throw new Error('fixture');
    await db.update(paymentSessions).set({expires_at:new Date(Date.now()-1000)}).where(eq(paymentSessions.payment_ref,payment.payment.payment_ref));
    const result = await repoCompleteIlanPayment(payment.payment.payment_ref,proof(payment.price,'late-'+id));
    expect(result.ok).toBe(false);
    expect((await repoMyPayment(payment.payment.payment_ref,a.id))?.state).toBe('refund_pending');
    expect(await db.select().from(ilanPurchases).where(eq(ilanPurchases.ilan_id,id))).toHaveLength(0);
  });
  it('duplicate package callbacks credit once; first balance creation is serialized', async () => {
    const a = await buyer();
    const [pack] = await repoGetCreditPackages();
    expect(pack).toBeDefined();
    const p = await repoCreateCreditPackagePayment(a.id,pack.key,'shopier');
    const q = await repoCreateCreditPackagePayment(a.id,pack.key,'shopier');
    if (!p.ok || !q.ok) throw new Error('fixture');
    const pProof = proof(Number(p.purchase.price),p.purchase.payment_ref);
    const qProof = proof(Number(q.purchase.price),q.purchase.payment_ref);
    await Promise.all([repoCompleteCreditPackagePayment(p.purchase.payment_ref,pProof),repoCompleteCreditPackagePayment(p.purchase.payment_ref,pProof),repoCompleteCreditPackagePayment(q.purchase.payment_ref,qProof)]);
    expect(await repoGetCreditBalance(a.id)).toBe(pack.credits*2);
    expect(await db.select().from(creditLedger).where(eq(creditLedger.user_id,a.id))).toHaveLength(2);
    await repoFailCreditPackagePayment(p.purchase.payment_ref);
    expect((await repoCompleteCreditPackagePayment(p.purchase.payment_ref,pProof)).ok).toBe(true);
  });
  it('own, expired and insufficient credit do not create purchases', async () => {
    const a = await buyer(), b = await buyer();
    const own = await listing(a.id), expired = await listing(a.id,'active',-1);
    expect((await repoPurchaseIlan(own,a.id,declaration,'127.0.0.1')).ok).toBe(false);
    expect((await repoPurchaseIlan(expired,b.id,declaration,'127.0.0.1')).ok).toBe(false);
    expect((await repoPurchaseIlan(own,b.id,declaration,'127.0.0.1')).ok).toBe(false);
    expect((await repoCreateIlanPayment(expired,b.id,'shopier',declaration,'127.0.0.1')).ok).toBe(false);
  });
});
