import type { FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { getAuthUserId, handleRouteError, parsePage } from '../_shared';
import { repoAddPaymentNote,repoAdjustCredits,repoAdminCredits,repoCommerceSummary,repoListPaymentOperations,repoPaymentOperation } from './operations.repository';
const filters=z.object({state:z.enum(['initializing','pending','completed','failed','review','refund_pending','refunded']).optional(),search:z.string().max(255).optional()}).passthrough();
export async function adminPayments(req:FastifyRequest,reply:FastifyReply){try{const q=filters.parse(req.query);const p=parsePage(req.query as Record<string,string>);return reply.send({...await repoListPaymentOperations({...q,...p}),page:p.page,limit:p.limit});}catch(e){return handleRouteError(reply,req,e,'payments_list');}}
export async function adminPayment(req:FastifyRequest,reply:FastifyReply){try{const {ref}=req.params as {ref:string};const row=await repoPaymentOperation(ref);return row?reply.send(row):reply.code(404).send({error:'not_found'});}catch(e){return handleRouteError(reply,req,e,'payment_detail');}}
export async function adminPaymentNote(req:FastifyRequest,reply:FastifyReply){try{const {note}=z.object({note:z.string().trim().min(5).max(2000)}).strict().parse(req.body);return reply.send(await repoAddPaymentNote((req.params as {ref:string}).ref,getAuthUserId(req),note));}catch(e){return handleRouteError(reply,req,e,'payment_note');}}
export async function adminCredits(req:FastifyRequest,reply:FastifyReply){try{const q=filters.parse(req.query),p=parsePage(req.query as Record<string,string>);return reply.send({...await repoAdminCredits(q.search??'',p.limit,p.offset),page:p.page,limit:p.limit});}catch(e){return handleRouteError(reply,req,e,'credits_list');}}
export async function adminCreditAdjustment(req:FastifyRequest,reply:FastifyReply){try{const body=z.object({id:z.string().uuid(),user_id:z.string().uuid(),delta:z.number().int().min(-10000).max(10000).refine(n=>n!==0),reason:z.string().trim().min(10).max(1000)}).strict().parse(req.body);return reply.send(await repoAdjustCredits(body,getAuthUserId(req)));}catch(e){return handleRouteError(reply,req,e,'credit_adjustment');}}
export async function adminCommerceSummary(req:FastifyRequest,reply:FastifyReply){try{return reply.send(await repoCommerceSummary());}catch(e){return handleRouteError(reply,req,e,'commerce_summary');}}
