"use client";
import {useState} from 'react';
import {Mail,Phone} from 'lucide-react';
import {createContact} from './contact.service';
import type {ContactFormData} from './contact.type';
import {Button} from '@/components/ui/Button';
const INITIAL_FORM:ContactFormData={name:'',email:'',phone:'',subject:'',message:''};
interface ContactInfo {company_name?:string;phone?:string;phone_2?:string;email?:string;email_2?:string;address?:string;city?:string;country?:string;working_hours?:string;maps_embed_url?:string}
export function ContactPageClient({contactInfo}:{contactInfo?:ContactInfo|null}){
 const [form,setForm]=useState(INITIAL_FORM),[saving,setSaving]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');
 const email=contactInfo?.email_2||contactInfo?.email;
 const phone=[contactInfo?.phone_2,contactInfo?.phone].find(p=>p&&!/0000000/.test(p.replace(/\D/g,'')));
 async function handleSubmit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(saving)return;setSaving(true);setError('');setDone(false);try{await createContact(form);setForm(INITIAL_FORM);setDone(true)}catch{setError('Mesaj gönderilemedi. Bilgileriniz korunuyor; tekrar deneyin.')}finally{setSaving(false)}}
 const inputClass='mt-2 w-full rounded-lg border border-border bg-background px-3 py-3 text-foreground focus-visible:outline-2 focus-visible:outline-brand';
 return <main className="site-container max-w-4xl py-10 sm:py-14"><header className="mb-8"><p className="text-sm text-brand">PaketJet destek</p><h1 className="mt-2 text-3xl font-semibold">Bize ulaşın</h1><p className="mt-3 text-muted">İlanınız, iletişim erişiminiz veya hesabınızla ilgili talebinizi iletin.</p></header>
 {(email||phone)&&<div className="mb-8 grid gap-4 sm:grid-cols-2">{email&&<a href={`mailto:${email}`} className="flex min-w-0 items-center gap-3 rounded-xl border border-border-soft bg-surface p-5"><Mail aria-hidden className="shrink-0 text-brand"/><span className="break-all">{email}</span></a>}{phone&&<a href={`tel:${phone.replace(/[^+\d]/g,'')}`} className="flex items-center gap-3 rounded-xl border border-border-soft bg-surface p-5"><Phone aria-hidden className="text-brand"/>{phone}</a>}</div>}
 {(contactInfo?.company_name||contactInfo?.address)&&<div className="mb-8 rounded-xl border border-border-soft bg-surface p-5"><h2 className="font-semibold">İletişim bilgileri</h2>{contactInfo.company_name&&<p className="mt-2">{contactInfo.company_name}</p>}{contactInfo.address&&<p className="mt-2 text-muted">{contactInfo.address}</p>}{contactInfo.working_hours&&<p className="mt-2 text-muted">{contactInfo.working_hours}</p>}</div>}
 <form method="post" onSubmit={handleSubmit} className="rounded-xl border border-border-soft bg-surface p-5 sm:p-8"><h2 className="mb-6 text-xl font-semibold">Mesaj gönderin</h2><div className="grid gap-5 sm:grid-cols-2">{([{key:'name',label:'Ad soyad',type:'text',auto:'name'},{key:'email',label:'E-posta',type:'email',auto:'email'},{key:'phone',label:'Telefon',type:'tel',auto:'tel'},{key:'subject',label:'Konu',type:'text',auto:'off'}] as const).map(f=><label key={f.key} htmlFor={`contact-${f.key}`} className="text-sm font-medium">{f.label}<input id={`contact-${f.key}`} name={f.key} type={f.type} autoComplete={f.auto} required maxLength={f.key==='subject'?200:100} value={form[f.key]} onChange={e=>setForm({...form,[f.key]:e.target.value})} className={inputClass}/></label>)}<label htmlFor="contact-message" className="text-sm font-medium sm:col-span-2">Mesajınız<textarea id="contact-message" name="message" required minLength={10} maxLength={5000} rows={6} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} className={inputClass}/></label></div>
 {error&&<p role="alert" className="mt-4 text-sm text-danger">{error}</p>}{done&&<p role="status" className="mt-4 text-sm text-success">Mesajınız alındı. Talebiniz destek ekibine iletildi.</p>}<Button type="submit" disabled={saving} className="mt-6">{saving?'Gönderiliyor…':'Mesajı gönder'}</Button></form></main>
}
