'use client';
import {ContentHistory} from './record-history';
import {useEffect,useState} from 'react';
import {useManagedRecordQuery,useManagedContentQuery,useSaveManagedContentMutation,useDeleteManagedContentMutation} from '@/integrations/hooks';
import {managedFields,type ManagedResource,type ManagedContent} from '@/integrations/shared';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const titles:Record<ManagedResource,string>={pages:'Sayfa ve yasal içerikler',faqs:'Sık sorulan sorular',tickets:'Destek talepleri'};
export default function ManagedContentPage({resource,initialId}:{resource:ManagedResource;initialId?:string}){
 const record=useManagedRecordQuery({resource,id:initialId??''},{skip:!initialId||initialId==='new'});
 const [offset,setOffset]=useState(0),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<ManagedContent|null>(null),[message,setMessage]=useState('');const list=useManagedContentQuery({resource,offset,search:query||undefined});const [remove,{isLoading:removing}]=useDeleteManagedContentMutation();
 useEffect(()=>{if(initialId==='new')setSelected({id:'',locale:'tr',module_key:'kurumsal',category:'genel',display_order:0,is_published:0});else if(record.data)setSelected(record.data);},[initialId,record.data]);
 return <Card><CardHeader><CardTitle>{titles[resource]}</CardTitle><CardDescription>{resource==='tickets'?'Kullanıcı talebini inceleyin, durumunu ve iç notları yönetin.':'İçerikleri, yayın durumlarını ve sıralamayı yönetin.'}</CardDescription></CardHeader><CardContent className="space-y-5"><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();setQuery(search);setOffset(0);}}>{resource!=='faqs'&&<><Input className="max-w-sm" aria-label="İçerik ara" placeholder="Ara" value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="outline">Ara</Button></>}<Button type="button" variant="outline" onClick={()=>list.refetch()}>Yenile</Button>{resource!=='tickets'&&<Button type="button" onClick={()=>setSelected({id:'',locale:'tr',module_key:'kurumsal',category:'genel',display_order:0,is_published:0})}>Yeni içerik</Button>}</form><output className="text-sm">{message}</output>{record.isError&&<p role="alert">İstenen kayıt bulunamadı veya alınamadı.</p>}{list.isError?<p role="alert">Kayıtlar yüklenemedi. Yenileyip tekrar deneyin.</p>:list.isLoading?<output>Yükleniyor…</output>:<ul className="divide-y rounded-lg border">{list.data?.map(row=><li key={row.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><h2 className="break-words font-medium">{row.title??row.question??row.subject}</h2><p className="mt-1 break-words text-sm text-muted-foreground">{resource==='tickets'?`${row.name} · ${row.email} · ${row.status}`:`${row.locale} · ${row.is_published?'Yayında':'Taslak'} · sıra ${row.display_order}`}</p></div><Button variant="outline" onClick={()=>setSelected(row)}>Düzenle</Button><Button variant="outline" disabled={removing} onClick={async()=>{if(!window.confirm('Kayıt kalıcı olarak silinecek. Devam edilsin mi?'))return;try{await remove({resource,id:row.id}).unwrap();setMessage('Kayıt silindi.');list.refetch();}catch{setMessage('Silinemedi. Tekrar deneyin.');}}}>Sil</Button></li>)}{!list.data?.length&&<li className="p-10 text-center text-sm text-muted-foreground">Kayıt bulunmuyor.</li>}</ul>}<div className="flex justify-between"><Button variant="outline" disabled={offset===0||list.isFetching} onClick={()=>setOffset(n=>n-20)}>Önceki</Button><span className="text-sm">Sayfa {offset/20+1}</span><Button variant="outline" disabled={(list.data?.length??0)<20||list.isFetching} onClick={()=>setOffset(n=>n+20)}>Sonraki</Button></div>{selected&&<ContentEditor resource={resource} row={selected} close={()=>setSelected(null)} saved={()=>{setSelected(null);setMessage('İçerik kaydedildi.');list.refetch();}}/>}</CardContent></Card>;
}
function ContentEditor({resource,row,close,saved}:{resource:ManagedResource;row:ManagedContent;close:()=>void;saved:()=>void}){
 const [form,setForm]=useState<Record<string,string|number|null>>({...row}),[dirty,setDirty]=useState(false),[error,setError]=useState('');const [save,{isLoading}]=useSaveManagedContentMutation();
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 const closeEditor=()=>{if(!dirty||window.confirm('Kaydedilmemiş değişiklikler var. Kapatılsın mı?'))close();};
 return <Dialog open onOpenChange={open=>{if(!open)closeEditor();}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{row.id?'İçeriği düzenle':'Yeni içerik'}</DialogTitle><DialogDescription>{resource==='tickets'?'Notlar yalnız yönetim ekibine görünür; bu form e-posta göndermez.':'Kaydetmeden önce yayın durumunu ve içeriği kontrol edin.'}</DialogDescription></DialogHeader>{resource==='tickets'&&<div className="rounded-md border p-4 text-sm"><p className="font-medium">{row.subject}</p><p className="mt-2 whitespace-pre-wrap break-words">{row.message}</p></div>}<form className="space-y-4" onSubmit={async e=>{e.preventDefault();const body:Record<string,string|number|null>={};for(const field of managedFields[resource])body[field.key]=field.type==='number'||field.key==='is_published'?Number(form[field.key]??0):form[field.key]??'';try{await save({resource,id:row.id||undefined,body}).unwrap();setDirty(false);saved();}catch{setError('Kaydedilemedi. Alanları ve URL adının benzersizliğini kontrol edin. Değişiklikleriniz korunuyor.');}}}>{managedFields[resource].map(field=><label htmlFor={`field-${field.key}`} key={field.key} className="block space-y-2 text-sm">{field.label}{field.required?' *':''}{field.type==='select'?<select id={`field-${field.key}`} className="flex h-10 w-full rounded-md border bg-background px-3" value={String(form[field.key]??field.options?.[0]?.[0]??'')} onChange={e=>{setDirty(true);setForm(f=>({...f,[field.key]:e.target.value}));}}>{field.options?.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>:field.type==='textarea'?<Textarea id={`field-${field.key}`} rows={field.key==='content'?12:4} required={field.required} maxLength={field.max} value={String(form[field.key]??'')} onChange={e=>{setDirty(true);setForm(f=>({...f,[field.key]:e.target.value}));}}/>:<Input id={`field-${field.key}`} required={field.required} type={field.type==='number'?'number':'text'} min={field.type==='number'?0:undefined} maxLength={field.max} value={String(form[field.key]??'')} onChange={e=>{setDirty(true);setForm(f=>({...f,[field.key]:e.target.value}));}}/>}</label>)}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={isLoading}>{isLoading?'Kaydediliyor…':'Kaydet'}</Button></form>{resource==='pages'&&row.id&&<ContentHistory id={row.id}/>}</DialogContent></Dialog>;
}
