'use client';
import {useState} from 'react';
import {useListPaymentOperationsQuery,usePaymentOperationQuery,useAddPaymentNoteMutation} from '@/integrations/hooks';
import {paymentStateLabels,formatIlanPurchaseDate,formatIlanPurchaseMoney} from '@/integrations/shared';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
export default function PaymentsPage(){
 const [page,setPage]=useState(1),[state,setState]=useState(''),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState('');
 const list=useListPaymentOperationsQuery({page,state:state||undefined,search:query||undefined});
 return <Card><CardHeader><CardTitle>Ödeme inceleme kuyruğu</CardTitle><CardDescription>Tahsilat, erişim teslimi ve iade takibi. Eski ve doğrulanmamış kayıtlar incelemede tutulur.</CardDescription></CardHeader><CardContent className="space-y-5">
 <form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search);}}><label htmlFor="control-1" className="space-y-2 text-sm">Referans veya kullanıcı kimliği<Input id="control-1" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ara"/></label><label htmlFor="control-2" className="space-y-2 text-sm">Durum<select id="control-2" className="flex h-10 rounded-md border bg-background px-3" value={state} onChange={e=>{setState(e.target.value);setPage(1);}}><option value="">Tümü</option>{Object.entries(paymentStateLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><Button type="submit" variant="outline">Filtrele</Button><Button type="button" variant="outline" disabled={list.isFetching} onClick={()=>list.refetch()}>Yenile</Button></form>
 {list.isError?<p role="alert">Ödeme kayıtları yüklenemedi. Yenile düğmesiyle tekrar deneyin.</p>:list.isLoading?<output>Ödemeler yükleniyor…</output>:<><div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Referans / zaman</TableHead><TableHead>İşlem</TableHead><TableHead>Tutar</TableHead><TableHead>Durum</TableHead><TableHead>İncele</TableHead></TableRow></TableHeader><TableBody>{list.data?.data.map(row=><TableRow key={row.payment_ref}><TableCell><span className="block max-w-64 break-all font-mono text-xs">{row.payment_ref}</span><span className="text-sm text-muted-foreground">{formatIlanPurchaseDate(row.created_at)}</span></TableCell><TableCell>{row.kind==='listing'?'İletişim alımı':row.kind==='credits'?'Hak paketi':'Eski işlem'}<span className="block text-sm text-muted-foreground">{row.provider}</span></TableCell><TableCell>{formatIlanPurchaseMoney(row.amount)}</TableCell><TableCell>{paymentStateLabels[row.state]??row.state}{row.error_code&&<span className="block max-w-56 break-words text-xs text-muted-foreground">{row.error_code}</span>}</TableCell><TableCell><Button variant="outline" onClick={()=>setSelected(row.payment_ref)}>Detay</Button></TableCell></TableRow>)}{!list.data?.data.length&&<TableRow><TableCell colSpan={5} className="py-10 text-center">Bu filtrede ödeme kaydı yok.</TableCell></TableRow>}</TableBody></Table></div><div className="flex items-center justify-between gap-3 text-sm"><span>{list.data?.total} işlem · Sayfa {page}</span><div className="flex gap-2"><Button variant="outline" disabled={page===1||list.isFetching} onClick={()=>setPage(p=>p-1)}>Önceki</Button><Button variant="outline" disabled={page*(list.data?.limit??20)>=(list.data?.total??0)||list.isFetching} onClick={()=>setPage(p=>p+1)}>Sonraki</Button></div></div></>}
 {selected&&<PaymentDetail reference={selected} onClose={()=>setSelected('')}/>}
 </CardContent></Card>;
}
function PaymentDetail({reference,onClose}:{reference:string;onClose:()=>void}){
 const detail=usePaymentOperationQuery(reference),[note,setNote]=useState(''),[message,setMessage]=useState('');const [addNote,{isLoading}]=useAddPaymentNoteMutation();
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Ödeme kaydı</DialogTitle><DialogDescription className="break-all">{reference}</DialogDescription></DialogHeader>{detail.isError?<p role="alert">Detay alınamadı. <Button variant="outline" onClick={()=>detail.refetch()}>Tekrar dene</Button></p>:!detail.data?<p>Yükleniyor…</p>:<div className="space-y-5"><dl className="grid grid-cols-[auto_1fr] gap-3 text-sm"><dt>Durum</dt><dd>{paymentStateLabels[detail.data.state]}</dd><dt>Tutar</dt><dd>{formatIlanPurchaseMoney(detail.data.amount)}</dd><dt>Kullanıcı</dt><dd className="break-all">{detail.data.user_id||'Eşleştirme gerekiyor'}</dd><dt>Sağlayıcı</dt><dd>{detail.data.provider}</dd><dt>İşlem kimliği</dt><dd className="break-all">{detail.data.provider_payment_id??'Doğrulanmış bildirim yok'}</dd><dt>Neden</dt><dd>{detail.data.error_code??'—'}</dd></dl><p className="rounded-md border p-3 text-sm text-muted-foreground">İade ve tahsilat sağlayıcı kayıtlarıyla doğrulanmalıdır. Not eklemek para veya hak hareketi oluşturmaz. Kart bilgisi veya parola yazmayın.</p><form className="space-y-3" onSubmit={async e=>{e.preventDefault();try{await addNote({ref:reference,note}).unwrap();setNote('');setMessage('Not kaydedildi.');detail.refetch();}catch{setMessage('Not kaydedilemedi. Tekrar deneyin.');}}}><label htmlFor="control-3" className="block space-y-2 text-sm">İnceleme notu / sağlayıcı destek referansı<Textarea id="control-3" required minLength={5} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><Button disabled={isLoading}>Notu kaydet</Button><output className="text-sm">{message}</output></form><div><h3 className="mb-3 font-medium">İşlem geçmişi</h3><ol className="space-y-3">{detail.data.events?.map(event=><li key={event.id} className="rounded-md border p-3 text-sm"><p>{event.event} · {formatIlanPurchaseDate(event.created_at)}</p><p className="break-all text-xs text-muted-foreground">{event.actor_id}</p><p className="mt-2 whitespace-pre-wrap break-words">{event.note}</p></li>)}{!detail.data.events?.length&&<li className="text-sm text-muted-foreground">Bu eski kayıt için yeni denetim olayı henüz yok.</li>}</ol></div></div>}</DialogContent></Dialog>;
}
