import { render, screen } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import ResultPage from '@/app/panel/ilan-alma-hakki/odeme-sonuc/page';
import { getPaymentStatus } from '@/modules/payments/payments.service';
const state=vi.hoisted(()=>({query:'status=success&amount=999999'}));
vi.mock('next/navigation',()=>({useSearchParams:()=>new URLSearchParams(state.query)}));
vi.mock('@/modules/payments/payments.service',()=>({getPaymentStatus:vi.fn()}));
beforeEach(()=>vi.clearAllMocks());
it('querystring success cannot claim payment or credit',()=>{state.query='status=success&amount=999999';render(<ResultPage/>);expect(screen.getByText('Ödeme referansı bulunamadı')).toBeInTheDocument();expect(screen.queryByText('İşlemin tamamlandı')).not.toBeInTheDocument();expect(getPaymentStatus).not.toHaveBeenCalled();});
it('only server-confirmed completed listing displays access link',async()=>{state.query='ref=owned';vi.mocked(getPaymentStatus).mockResolvedValue({payment_ref:'owned',kind:'listing',ilan_id:'listing-1',amount:'50',state:'completed',error_code:null});render(<ResultPage/>);expect(await screen.findByText('İşlemin tamamlandı')).toBeInTheDocument();expect(screen.getByRole('link',{name:'İletişim bilgilerini gör'})).toHaveAttribute('href','/ilanlar/listing-1');});
it('paid but undelivered payment displays review, not success',async()=>{state.query='ref=review';vi.mocked(getPaymentStatus).mockResolvedValue({payment_ref:'review',kind:'listing',ilan_id:'listing-1',amount:'50',state:'refund_pending',error_code:'delivery_unavailable'});render(<ResultPage/>);expect(await screen.findByText('Ödemen inceleniyor')).toBeInTheDocument();expect(screen.queryByText('İşlemin tamamlandı')).not.toBeInTheDocument();});
