'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {getMyPurchases} from '@/modules/purchases/purchases.service';
import type {MyPurchase} from '@/modules/purchases/purchases.type';
import {Button} from '@/components/ui/Button';
import {formatDate} from '@/lib/date';
import {ROUTES} from '@/config/routes';
export default function PurchasesPage(){
 const [rows,setRows]=useState<MyPurchase[]|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=useCallback(async()=>{setError('');try{setRows((await getMyPurchases()).data);}catch{setError('Satın aldığın iletişimler yüklenemedi. Tekrar dene.');}},[]);useEffect(()=>{void load();},[load]);
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold">Satın aldıklarım</h1><p className="mt-2 text-sm text-muted">Açtığın taşıyıcı iletişimleri burada saklanır. Tekrar görüntülemek hak harcamaz.</p></div><Button variant="outline" onClick={load}>Yenile</Button></div>{error&&<p role="alert" className="rounded-lg border border-danger/30 p-4">{error}</p>}<p role="status" className="text-sm">{message}</p>{!rows&&!error?<p role="status">İletişimler yükleniyor…</p>:rows?.length===0?<section className="rounded-lg border border-border bg-surface p-10 text-center"><h2 className="text-lg font-semibold">Henüz iletişim açmadın.</h2><p className="mt-2 text-sm text-muted">Gönderine uygun bir güzergâh bulmak için güncel ilanları incele.</p><Link href={ROUTES.ilanlar.list} className="mt-5 inline-flex rounded-lg bg-action px-5 py-3 font-semibold text-white">İlanları incele</Link></section>:rows?.map(row=><article key={row.id} className="rounded-lg border border-border bg-surface p-6"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-border pb-4"><div><h2 className="text-xl font-semibold">{row.from_city} → {row.to_city}</h2><p className="mt-1 text-sm text-muted">Alım: {formatDate(row.created_at)}</p></div><Link href={ROUTES.ilanlar.detail(row.ilan_id)} className="py-2 font-medium text-brand">İlana dön</Link></div>{row.contact?<dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-sm text-muted">İrtibat kişisi</dt><dd className="mt-1">{row.contact.name||'Belirtilmemiş'}</dd></div><div><dt className="text-sm text-muted">Telefon</dt><dd className="mt-1 flex flex-wrap items-center gap-3">{row.contact.phone?<><a className="py-2 font-medium text-brand" href={`tel:${row.contact.phone.replace(/[^+0-9]/g,'')}`}>{row.contact.phone}</a><button className="rounded-lg border border-border px-3 py-2 text-sm" onClick={async()=>{try{await navigator.clipboard.writeText(row.contact!.phone!);setMessage('Telefon numarası kopyalandı.');}catch{setMessage('Kopyalanamadı. Numarayı seçerek kopyalayabilirsin.');}}}>Kopyala</button></>:'Belirtilmemiş'}</dd></div>{row.contact.email&&<div><dt className="text-sm text-muted">E-posta</dt><dd className="mt-1 break-all"><a className="py-2 text-brand" href={`mailto:${row.contact.email}`}>{row.contact.email}</a></dd></div>}{row.contact.address&&<div><dt className="text-sm text-muted">Adres</dt><dd className="mt-1 break-words">{row.contact.address}</dd></div>}</dl>:<p className="mt-4 text-danger">İletişim kaydı alınamadı. Destekle görüşürken işlem numaranı ilet: {row.id}</p>}</article>)}</div>;
}
