'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { createIlan, getOwnedIlan, updateIlan } from '@/modules/ilan/ilan.service';
import type { CreateIlanInput } from '@/modules/ilan/ilan.type';
import { Input } from '@/components/ui/Input';
import { TURKEY_CITIES } from '@/data/turkey-cities';
import { useAuthStore } from '@/modules/auth/auth.store';
import { parseApiDate } from '@/lib/date';
const field='mt-2 h-12 w-full rounded-lg border border-border bg-surface px-3 text-base';
const initial:CreateIlanInput={from_city:'',to_city:'',departure_date:'',vehicle_type:'car',contact_phone:'',title:'',description:'',contact_name:'',contact_email:''};
function localTime(iso:string){const date=parseApiDate(iso);return new Date(date.getTime()+3*3600000).toISOString().slice(0,16);}
export default function IlanVerForm({onSuccess,editId}:{onSuccess?:()=>void;editId?:string}={}) {
  const {user}=useAuthStore();
  const [form,setForm]=useState<CreateIlanInput>(initial),[departure,setDeparture]=useState(''),[arrival,setArrival]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false),[loading,setLoading]=useState(!!editId);
  const submitLock=useRef(false);
  useEffect(()=>{if(editId){getOwnedIlan(editId).then(i=>{if(['sold','removed'].includes(i.status))throw new Error('Kapalı ilan düzenlenemez.');setForm({from_city:i.from_city,to_city:i.to_city,from_district:i.from_district??'',to_district:i.to_district??'',departure_date:i.departure_date,vehicle_type:i.vehicle_type,title:i.title??'',description:i.description??'',contact_phone:i.contact_phone??'',contact_email:i.contact_email??'',contact_name:i.contact_name??'',contact_address:i.contact_address??''});setDeparture(localTime(i.departure_date));if(i.arrival_date)setArrival(localTime(i.arrival_date));}).catch(()=>setError('İlan yüklenemedi veya düzenlemeye kapalı.')).finally(()=>setLoading(false));}else setForm(f=>({...f,contact_phone:user?.phone??'',contact_email:user?.email??'',contact_name:user?.full_name??''}));},[editId,user]);
  function update<K extends keyof CreateIlanInput>(key:K,value:CreateIlanInput[K]){setForm(f=>({...f,[key]:value}));}
  async function submit(e:React.FormEvent){e.preventDefault();if(submitLock.current)return;setError('');const date=new Date(`${departure}:00+03:00`);if(Number.isNaN(date.getTime())||date.getTime()<=Date.now()){setError('Hareket tarihi gelecekte olmalı. Saatler Türkiye saatidir.');return;}const end=arrival?new Date(`${arrival}:00+03:00`):null;if(end&&(Number.isNaN(end.getTime())||end<date)){setError('Varış zamanı hareketten önce olamaz.');return;}submitLock.current=true;setBusy(true);try{const data={...form,departure_date:date.toISOString(),arrival_date:end?.toISOString(),contact_email:form.contact_email||undefined};if(editId)await updateIlan(editId,data);else await createIlan(data);setSuccess(true);}catch(e){setError((e as {code?:string}).code==='payment_pending'?'Bu ilan için ödeme bekleniyor. Düzenleme şu anda yapılamıyor.':'İlan kaydedilemedi. Alanları kontrol edip yeniden deneyin.');}finally{setBusy(false);submitLock.current=false;}}
  if(loading)return <p role="status">İlan yükleniyor…</p>;
  if(success)return <section role="status" className="rounded-lg border border-border p-8"><h2 className="text-2xl font-semibold">İlanın incelemeye gönderildi</h2><p className="mt-4 leading-7 text-muted">Onaylandıktan sonra yayımlanacak. Durumunu İlanlarım ekranından takip edebilirsin.</p>{onSuccess?<button className="mt-6 min-h-12 text-brand" onClick={onSuccess}>İlanlarıma git</button>:<Link href="/panel/ilanlarim" className="mt-6 inline-flex min-h-12 items-center text-brand">İlanlarıma git</Link>}</section>;
  return <form onSubmit={submit} className="space-y-5">{error&&<div role="alert" className="rounded-lg border border-danger p-4 text-danger">{error}</div>}
    <fieldset className="rounded-lg border border-border bg-surface p-5 sm:p-6"><legend className="px-2 text-xl font-semibold">Rota ve tarih</legend><div className="grid gap-5 sm:grid-cols-2">{(['from','to'] as const).map(prefix=>{const city=form[`${prefix}_city`];const districts=TURKEY_CITIES.find(c=>c.value===city)?.districts??[];return <div key={prefix}><label htmlFor={`${prefix}-city`} className="text-sm font-medium">{prefix==='from'?'Nereden':'Nereye'}<select id={`${prefix}-city`} aria-label={prefix==='from'?'Nereden':'Nereye'} required value={city} onChange={e=>{update(`${prefix}_city`,e.target.value);update(`${prefix}_district`,'');}} className={field}><option value="">İl seçin</option>{TURKEY_CITIES.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label><label className="mt-4 block text-sm font-medium">{prefix==='from'?'Kalkış ilçesi':'Varış ilçesi'} <span className="font-normal text-muted">(isteğe bağlı)</span><select value={form[`${prefix}_district`]??''} disabled={!city} onChange={e=>update(`${prefix}_district`,e.target.value)} className={field}><option value="">İlçe seçin</option>{districts.map(d=><option key={d}>{d}</option>)}</select></label></div>;})}<Input label="Hareket tarihi ve saati" type="datetime-local" required value={departure} onChange={e=>setDeparture(e.target.value)} hint="Türkiye saati (UTC+3)"/><Input label="Varış tarihi ve saati (isteğe bağlı)" type="datetime-local" value={arrival} onChange={e=>setArrival(e.target.value)}/></div></fieldset>
    <fieldset className="rounded-lg border border-border bg-surface p-5 sm:p-6"><legend className="px-2 text-xl font-semibold">Araç ve açıklama</legend><div className="space-y-5"><label className="block text-sm font-medium">Araç tipi<select value={form.vehicle_type} onChange={e=>update('vehicle_type',e.target.value as CreateIlanInput['vehicle_type'])} className={field}><option value="car">Otomobil</option><option value="van">Kamyonet</option><option value="truck">Kamyon</option><option value="motorcycle">Motosiklet</option><option value="other">Diğer</option></select></label><Input label="İlan başlığı" maxLength={255} value={form.title} onChange={e=>update('title',e.target.value)} placeholder="Kısa ve net bir başlık yazın"/><label className="block text-sm font-medium">Açıklama<textarea rows={4} maxLength={4000} value={form.description} onChange={e=>update('description',e.target.value)} className="mt-2 w-full rounded-lg border border-border bg-surface p-3 text-base" placeholder="Aracınız ve güzergâhınızla ilgili ayrıntıları yazın."/></label><p className="text-sm text-muted">Telefon ve e-posta bilgilerini açıklamaya yazma; aşağıdaki özel iletişim alanını kullan.</p></div></fieldset>
    <fieldset className="rounded-lg border border-border bg-surface p-5 sm:p-6"><legend className="px-2 text-xl font-semibold">Özel iletişim</legend><div className="space-y-5"><Input label="Ad soyad" required maxLength={160} autoComplete="name" value={form.contact_name} onChange={e=>update('contact_name',e.target.value)}/><div className="grid gap-5 sm:grid-cols-2"><Input label="Telefon" required type="tel" pattern="\+?[0-9 ()\-]{10,25}" autoComplete="tel" value={form.contact_phone} onChange={e=>update('contact_phone',e.target.value)}/><Input label="E-posta" type="email" autoComplete="email" value={form.contact_email} onChange={e=>update('contact_email',e.target.value)}/></div><p className="text-sm leading-6 text-muted">Bu bilgiler yalnız ilanını satın alan kişiye açılır.</p></div></fieldset>
    <details className="rounded-lg border border-border p-5"><summary className="font-medium">Önizlemeyi göster</summary><p className="mt-4 font-semibold">{form.from_city||'Kalkış'} → {form.to_city||'Varış'}</p><p className="mt-2 text-muted">{form.title}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm text-muted">{form.description}</p></details>
    <button disabled={busy} className="min-h-12 w-full rounded-lg bg-action px-5 font-semibold text-white disabled:opacity-60">{busy?'Gönderiliyor…':'İncelemeye gönder'}</button><p className="text-center text-sm text-muted">İlanın onaylandıktan sonra yayımlanır.</p>
  </form>;
}
