-- Product copy only. Legal texts, contact identity and financial balances are preserved.
UPDATE site_settings SET value=JSON_SET(value,'$.title','PaketJet — Taşıyıcı ilanları','$.description','Güzergâhına uygun taşıyıcı ilanını bul, iletişim bilgilerine eriş ve doğrudan görüş. İlan vermek ücretsizdir.')
WHERE `key` IN ('site_meta_default','paketjet__site_meta_default') AND JSON_VALID(value);
UPDATE site_settings SET value=JSON_SET(value,'$.title_default','PaketJet — Taşıyıcı ilanları','$.title_template','%s | PaketJet','$.description','Taşıyıcı güzergâhlarını keşfet, iletişim bilgilerine eriş ve doğrudan görüş.')
WHERE `key` IN ('site_seo','paketjet__site_seo') AND JSON_VALID(value);
UPDATE site_settings SET value=JSON_SET(value,'$.title','Yoluna uygun taşıyıcıyı bul','$.subtitle','Güzergâhına uygun ilanı bul, iletişim bilgilerine eriş ve taşıyıcıyla doğrudan görüş.','$.ctaLabel','İlanları keşfet','$.ctaPath','/ilanlar','$.ctaSecondaryLabel','Ücretsiz ilan ver','$.ctaSecondaryPath','/ilan-ver','$.bgImage','','$.bgImageDark','')
WHERE `key` IN ('homepage_hero','paketjet__homepage_hero') AND JSON_VALID(value);
UPDATE site_settings SET value='PaketJet, taşıyıcı güzergâh ilanlarını keşfetmeni ve iletişim bilgilerine erişmeni sağlar. Taşıma koşullarını taraflar doğrudan görüşür.' WHERE `key` IN ('footer_about','paketjet__footer_about');
UPDATE custom_pages_i18n SET content='<h2>PaketJet nasıl çalışır?</h2><p>Taşıyıcılar güzergâh, hareket tarihi ve araç bilgileriyle ücretsiz ilan verir. Göndericiler uygun ilanı arar, iletişim bilgilerine erişim satın alır veya ilan alma hakkını kullanır.</p><h2>Doğrudan iletişim</h2><p>İletişim bilgileri açıldıktan sonra taraflar taşımanın kapsamını, ücretini ve teslim koşullarını doğrudan görüşür. İletişim erişimi ücreti taşıma ücreti değildir.</p><h2>İlan yönetimi</h2><p>Yeni ve düzenlenen ilanlar incelemeye alınır. Güncel ilanları rota ve tarihe göre arayabilirsin. Daha önce satın aldığın iletişim bilgilerine hesabındaki Satın aldıklarım ekranından dönebilirsin.</p>', summary='Taşıyıcı güzergâhlarını keşfet, iletişim bilgilerine eriş ve doğrudan görüş.',meta_description='PaketJet taşıyıcı ilanları ve iletişim erişimi platformu hakkında bilgi alın.' WHERE slug='hakkimizda' AND locale='tr';
UPDATE custom_pages SET updated_at=CURRENT_TIMESTAMP(3) WHERE id IN (SELECT page_id FROM custom_pages_i18n WHERE slug='hakkimizda' AND locale='tr');
