-- 30 clearly labelled, non-purchasable examples. Re-running preserves edits and dates.
-- In production apply ONLY after sample purchase guards are deployed.
INSERT INTO users (id,email,password_hash,full_name,is_active,email_verified) VALUES ('e09a0000-0000-4000-8000-000000000000','samples@paketjet.invalid','!disabled-sample-account-no-login','Örnek ilanlar',0,0) ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000001', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-01-istanbul-ankara', 1, 'İstanbul', 'Ankara', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 4 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 5 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Kapalı kasada şehirler arası koli taşımacılığı', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Ambalajlı ev eşyaları ve orta boy koliler için örnek kamyonet güzergâhı. Yüklerin ölçüsü ve teslim noktası yolculuk öncesinde netleştirilir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000002', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-02-ankara-istanbul', 1, 'Ankara', 'İstanbul', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 5 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 6 DAY), 0, 0, 0, 'car', 'ÖRNEK İLAN — Küçük paketler için dönüş yolculuğu', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Otomobil bagajına sığan kitap, tekstil ve kişisel eşya kolileri için örnek dönüş rotası. Kırılabilir ürünlerin koruyucu ambalajla hazırlanması beklenir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000003', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-03-istanbul-izmir', 1, 'İstanbul', 'İzmir', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 6 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 7 DAY), 0, 0, 0, 'truck', 'ÖRNEK İLAN — Paletli ürünler için Ege güzergâhı', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Paletli ve düzenli istiflenmiş ticari ürünler için örnek kamyon yolculuğu. Yükleme ekipmanı ve boşaltma koşulları önceden planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000004', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-04-izmir-istanbul', 1, 'İzmir', 'İstanbul', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 7 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 8 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Mağaza ürünleri için kapalı kasa', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kutulanmış mağaza ürünleri ve sezonluk tekstil gönderileri için örnek rota. Teslim edilecek koli adedi ve paket ölçüleri önceden paylaşılır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000005', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-05-ankara-izmir', 1, 'Ankara', 'İzmir', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 8 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 9 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Öğrenci eşyaları için şehirler arası rota', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kitap kolileri, kıyafetler ve demonte küçük mobilyalar için örnek güzergâh. Parçaların ayrı ambalajlanması ve kolilerin etiketlenmesi planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000006', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-06-izmir-ankara', 1, 'İzmir', 'Ankara', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 9 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 10 DAY), 0, 0, 0, 'car', 'ÖRNEK İLAN — Kitap ve küçük eşya kolileri', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Bagaj hacmine uygun küçük paketlerle örnek otomobil yolculuğu. Sıvı, dökülebilir ve özel taşıma koşulu gerektiren ürünler kapsam dışındadır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000007', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-07-bursa-istanbul', 1, 'Bursa', 'İstanbul', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 10 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 11 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Atölyeden mağazaya ürün sevkiyatı', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Ambalajlı atölye ürünleri ve hafif ekipman için örnek Marmara rotası. Yükleme sırası, ürün ölçüleri ve teslim saat aralığı birlikte belirlenir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000008', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-08-istanbul-bursa', 1, 'İstanbul', 'Bursa', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 11 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 12 DAY), 0, 0, 0, 'truck', 'ÖRNEK İLAN — Demonte mobilya ve ekipman rotası', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Koruyucu malzemeyle sarılmış demonte mobilyalar için örnek kamyon güzergâhı. Kat taşıması ve montajın ayrıca değerlendirilmesi gerekir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000009', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-09-antalya-istanbul', 1, 'Antalya', 'İstanbul', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 12 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 13 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Sezonluk eşyalar için dönüş güzergâhı', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kutulanmış sezonluk ev eşyaları ve tekstil ürünleri için örnek uzun yol rotası. Birden fazla koli varsa içerik listesi hazırlanması önerilir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000010', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-10-istanbul-antalya', 1, 'İstanbul', 'Antalya', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 13 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 14 DAY), 0, 0, 0, 'truck', 'ÖRNEK İLAN — İşletme ekipmanları için Akdeniz rotası', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Ambalajlı raf parçaları ve işletme ekipmanları için örnek güzergâh. Ürünlerin araca sabitlenmesi ve yükleme alanına erişim önceden planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000011', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-11-konya-ankara', 1, 'Konya', 'Ankara', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 14 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 15 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Paketli yedek parça gönderimi', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Temizlenmiş, kutulanmış ve sızıntı riski bulunmayan yedek parçalar için örnek rota. Her kutunun ölçüsü ve ağırlığı yolculuktan önce paylaşılır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000012', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-12-ankara-konya', 1, 'Ankara', 'Konya', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 15 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 16 DAY), 0, 0, 0, 'car', 'ÖRNEK İLAN — Kompakt koliler için İç Anadolu rotası', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Küçük hacimli ev eşyaları ve kitap paketleri için örnek otomobil güzergâhı. Teslim noktaları şehir içi erişime uygun şekilde planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000013', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-13-adana-mersin', 1, 'Adana', 'Mersin', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 16 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 17 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Kısa mesafede mağaza kolileri', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Ambalajlı perakende ürünleri için örnek bölgesel kamyonet rotası. Koli sayısı, yükleme alanı ve teslimat sırası önceden netleştirilir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000014', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-14-mersin-adana', 1, 'Mersin', 'Adana', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 17 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 18 DAY), 0, 0, 0, 'car', 'ÖRNEK İLAN — Küçük paketlerle bölgesel dönüş', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Otomobil bagajına uygun tekstil ve kitap kolileri için örnek dönüş güzergâhı. Açıkta ürün yerine kapalı ve etiketli ambalaj kullanılır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000015', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-15-gaziantep-adana', 1, 'Gaziantep', 'Adana', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 18 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 19 DAY), 0, 0, 0, 'truck', 'ÖRNEK İLAN — Paletli ambalaj malzemeleri', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Paketli ambalaj ve depo malzemeleri için örnek kamyon rotası. Palet ölçüleri, istif yüksekliği ve yükleme desteği önceden değerlendirilir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000016', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-16-adana-gaziantep', 1, 'Adana', 'Gaziantep', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 19 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 20 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Atölye malzemeleri için kapalı kasa', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kutulanmış el aletleri ve tehlikeli madde içermeyen atölye malzemeleri için örnek güzergâh. Keskin parçalar koruyucu ambalajla ayrılır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000017', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-17-kayseri-ankara', 1, 'Kayseri', 'Ankara', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 20 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 21 DAY), 0, 0, 0, 'truck', 'ÖRNEK İLAN — Mobilya parçaları için şehirler arası rota', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Demonte ve ambalajlı mobilya parçaları için örnek taşıma planı. Cam parçalar ayrı korunur; parça sayısı teslim öncesinde kayıt altına alınır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000018', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-18-ankara-eskisehir', 1, 'Ankara', 'Eskişehir', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 21 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 22 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Ev ve ofis kolileri için güzergâh', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kutulanmış ofis malzemeleri ve kişisel eşyalar için örnek rota. Belgeler kapalı kutularda, elektronik ürünler kendi koruyucu ambalajında hazırlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000019', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-19-eskisehir-istanbul', 1, 'Eskişehir', 'İstanbul', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 22 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 23 DAY), 0, 0, 0, 'car', 'ÖRNEK İLAN — Öğrenci kolileri için dönüş rotası', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kitap, kıyafet ve küçük ev eşyaları için örnek otomobil yolculuğu. Bagaj ölçüsünü aşmayan kolilerle buluşma noktası önceden planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000020', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-20-kocaeli-ankara', 1, 'Kocaeli', 'Ankara', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 23 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 24 DAY), 0, 0, 0, 'truck', 'ÖRNEK İLAN — Paketli sanayi ürünleri için rota', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Tehlikeli madde içermeyen paketli sanayi ürünleri için örnek güzergâh. Yük sabitleme, palet ölçüsü ve boşaltma ekipmanı önceden değerlendirilir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000021', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-21-sakarya-bursa', 1, 'Sakarya', 'Bursa', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 24 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 25 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Üreticiden depoya koli gönderimi', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kutulanmış üretim malzemeleri ve hafif ticari ürünler için örnek Marmara rotası. Depo giriş koşulları ve teslim saat aralığı önceden belirlenir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000022', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-22-denizli-izmir', 1, 'Denizli', 'İzmir', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 25 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 26 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Tekstil kolileri için Ege rotası', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Paketli havlu, ev tekstili ve giyim ürünleri için örnek güzergâh. Kolilerin kuru ve kapalı ambalajda, ürün gruplarına göre etiketli olması planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000023', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-23-izmir-mugla', 1, 'İzmir', 'Muğla', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 26 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 27 DAY), 0, 0, 0, 'car', 'ÖRNEK İLAN — Yazlık eşyaları için küçük paket rotası', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kıyafet, kitap ve küçük dekorasyon paketleri için örnek otomobil yolculuğu. Kırılabilir eşyalar ayrı korunur ve teslim noktası önceden netleştirilir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000024', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-24-mugla-antalya', 1, 'Muğla', 'Antalya', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 27 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 28 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Ambalajlı işletme ürünleri', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kutulanmış tekstil ve küçük işletme malzemeleri için örnek sahil güzergâhı. Ara durak ve yükleme koşulları yolculuk öncesinde planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000025', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-25-samsun-ankara', 1, 'Samsun', 'Ankara', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 28 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 29 DAY), 0, 0, 0, 'truck', 'ÖRNEK İLAN — Depo kolileri için Karadeniz bağlantısı', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Düzenli istiflenmiş ticari koliler ve paketli depo malzemeleri için örnek rota. Ağır kutuların konumu ve boşaltma sırası önceden belirlenir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000026', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-26-trabzon-samsun', 1, 'Trabzon', 'Samsun', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 29 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 30 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Kıyı güzergâhında paketli eşya', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Ambalajlı ev eşyaları ve küçük mağaza kolileri için örnek Karadeniz rotası. Nemden etkilenebilen ürünler uygun koruyucu ambalajla hazırlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000027', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-27-erzurum-ankara', 1, 'Erzurum', 'Ankara', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 30 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 31 DAY), 0, 0, 0, 'truck', 'ÖRNEK İLAN — Uzun yol için ambalajlı ticari ürünler', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Paketli ve sabitlenebilir ticari yükler için örnek şehirler arası güzergâh. Ürün listesi, yükleme desteği ve teslim koşulları önceden paylaşılır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000028', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-28-diyarbakir-gaziantep', 1, 'Diyarbakır', 'Gaziantep', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 31 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 32 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Bölgesel mağaza ve atölye kolileri', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kutulanmış mağaza ürünleri ve hafif atölye malzemeleri için örnek rota. Koli ölçülerinin ve teslim noktalarının yolculuktan önce bildirilmesi planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000029', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-29-istanbul-tekirdag', 1, 'İstanbul', 'Tekirdağ', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 32 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 33 DAY), 0, 0, 0, 'van', 'ÖRNEK İLAN — Trakya güzergâhında ev eşyası kolileri', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Ambalajlı kişisel eşyalar ve demonte küçük raflar için örnek rota. Her parçanın etiketlenmesi ve yükleme alanına hazır getirilmesi planlanır.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO ilanlar (id,user_id,slug,is_sample,from_city,to_city,departure_date,arrival_date,total_capacity_kg,available_capacity_kg,price_per_kg,vehicle_type,title,description,contact_phone,contact_name,status) VALUES ('e09a0000-0000-4000-8000-000000000030', 'e09a0000-0000-4000-8000-000000000000', 'ornek-ilan-30-balikesir-izmir', 1, 'Balıkesir', 'İzmir', DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 33 DAY), DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 34 DAY), 0, 0, 0, 'car', 'ÖRNEK İLAN — Küçük koliler için Ege dönüşü', 'ÖRNEK İLANDIR. Gerçek taşıma hizmeti veya iletişim satışı sunmaz. Tarih, araç ve güzergâh bilgileri tanıtım amaçlıdır.

Kitap, tekstil ve bagaj boyutuna uygun kişisel eşyalar için örnek dönüş yolculuğu. Paketlerin kapalı ve taşımaya hazır olması beklenir.', '', 'Örnek taşıyıcı', 'active') ON DUPLICATE KEY UPDATE id=id;
