'use client';
import {useRef,useState} from 'react';
import {useCreditAccountsQuery,useAdjustCreditsMutation} from '@/integrations/hooks';
import type {CreditAccount} from '@/integrations/shared';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function CreditsPage(){
 const [page,setPage]=useState(1),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState<CreditAccount|null>(null);
 const list=useCreditAccountsQuery({page,search:query});
 return <Card><CardHeader><CardTitle>İlan alma hakları</CardTitle><CardDescription>Bakiyeler adet cinsindedir. Eski TL cüzdanları ayrı arşivde tutulur.</CardDescription></CardHeader><CardContent className="space-y-5"><form className="flex gap-3" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(1);}}><Input aria-label="E-posta veya kullanıcı kimliği" placeholder="E-posta veya kullanıcı kimliği" value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="outline">Ara</Button><Button type="button" variant="outline" onClick={()=>list.refetch()}>Yenile</Button></form>{list.isError?<p role="alert">Hak hesapları yüklenemedi.</p>:list.isLoading?<output>Yükleniyor…</output>:<><ul className="divide-y rounded-lg border">{list.data?.data.map(row=><li key={row.user_id} className="flex flex-wrap items-center gap-4 p-4"><div className="min-w-0 flex-1"><p className="break-all">{row.email}</p><p className="break-all text-xs text-muted-foreground">{row.user_id}</p></div><span>{row.balance} hak</span><Button variant="outline" onClick={()=>setSelected(row)}>Düzenle</Button></li>)}{!list.data?.data.length&&<li className="p-8 text-center">Hesap bulunamadı.</li>}</ul><div className="flex justify-between gap-3"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Önceki</Button><span className="text-sm">{list.data?.total} hesap · Sayfa {page}</span><Button variant="outline" disabled={page*(list.data?.limit??20)>=(list.data?.total??0)} onClick={()=>setPage(p=>p+1)}>Sonraki</Button></div></>}{selected&&<Adjustment account={selected} close={()=>setSelected(null)} saved={()=>list.refetch()}/>}</CardContent></Card>;
}
function Adjustment({account,close,saved}:{account:CreditAccount;close:()=>void;saved:()=>void}){
 const [delta,setDelta]=useState(''),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[done,setDone]=useState(false);const id=useRef(crypto.randomUUID());const [adjust,{isLoading}]=useAdjustCreditsMutation();
 return <Dialog open onOpenChange={open=>{if(!open)close();}}><DialogContent><DialogHeader><DialogTitle>Hak düzeltmesi</DialogTitle><DialogDescription>{account.email} · Mevcut bakiye: {account.balance} hak</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{const result=await adjust({id:id.current,user_id:account.user_id,delta:Number(delta),reason}).unwrap();setMessage(`Kaydedildi. Yeni bakiye: ${result.balance} hak.`);setDone(true);saved();}catch{setMessage('Düzeltme yapılamadı. Bakiye ve gerekçeyi kontrol edin; aynı işlem kimliğiyle tekrar deneyebilirsiniz.');}}}><label htmlFor="control-1" className="block space-y-2 text-sm">Eklenecek / düşülecek hak<Input id="control-1" required type="number" step="1" min="-10000" max="10000" value={delta} disabled={isLoading||done} onChange={e=>setDelta(e.target.value)}/></label><label htmlFor="control-2" className="block space-y-2 text-sm">Gerekçe ve kayıt referansı<Textarea id="control-2" required minLength={10} maxLength={1000} value={reason} disabled={isLoading||done} onChange={e=>setReason(e.target.value)}/></label><p className="text-sm text-muted-foreground">İşlemi yapan yönetici ve gerekçe denetim kaydında saklanır.</p><Button disabled={isLoading||done||Number(delta)===0}>Düzeltmeyi kaydet</Button><output className="text-sm">{message}</output></form></DialogContent></Dialog>;
}
