'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {getMyIlans,updateIlanStatus,deleteIlan} from '@/modules/ilan/ilan.service';
import type {Ilan} from '@/modules/ilan/ilan.type';
import {Badge} from '@/components/ui/Badge';
import {Button} from '@/components/ui/Button';
import {formatDate} from '@/lib/date';
import {ROUTES} from '@/config/routes';
const labels:Record<string,string>={active:'Yayında',pending_approval:'İncelemede',paused:'Durduruldu',sold:'Satıldı',expired:'Süresi doldu',cancelled:'Kapatıldı',removed:'Arşivlendi',completed:'Tamamlandı'};
const effectiveStatus=(row:Ilan)=>['active','pending_approval'].includes(row.status)&&new Date(row.departure_date).getTime()<=Date.now()?'expired':row.status;
export default function MyListings(){
 const [rows,setRows]=useState<Ilan[]|null>(null),[error,setError]=useState(''),[filter,setFilter]=useState(''),[busy,setBusy]=useState('');
 const load=useCallback(async()=>{setError('');try{setRows(await getMyIlans());}catch{setError('İlanların yüklenemedi. Tekrar dene.');}},[]);useEffect(()=>{void load();},[load]);
 async function action(id:string,kind:'pause'|'archive'){setBusy(id);setError('');try{if(kind==='pause')await updateIlanStatus(id,'paused');else await deleteIlan(id);await load();}catch{setError('İşlem tamamlanamadı. İlan satılmış veya ödeme için ayrılmış olabilir. Yenileyip tekrar dene.');}finally{setBusy('');}}
 const visible=rows?.filter(row=>!filter||effectiveStatus(row)===filter);
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold">İlanlarım</h1><p className="mt-2 text-sm text-muted">Taşıyıcı olarak paylaştığın güzergâhlar ve yayın durumları.</p></div><Link href={ROUTES.ilanVer} className="rounded-lg bg-action px-5 py-3 font-semibold text-white">Ücretsiz ilan ver</Link></div><div className="flex flex-wrap items-end gap-3"><label className="text-sm">İlan durumu<select value={filter} onChange={e=>setFilter(e.target.value)} className="mt-2 block rounded-lg border border-border bg-surface px-3 py-3"><option value="">Tüm ilanlar</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><Button variant="outline" onClick={load}>Yenile</Button></div>{error&&<p role="alert" className="rounded-lg border border-danger/30 bg-danger/5 p-4">{error}</p>}{!rows&&!error?<p role="status">İlanlar yükleniyor…</p>:<div className="space-y-3">{visible?.map(row=>{const state=effectiveStatus(row),editable=!['sold','removed','completed'].includes(state);return <article key={row.id} className="flex flex-col gap-4 rounded-lg border border-border bg-surface p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-semibold">{row.from_city} → {row.to_city}</h2><Badge color={state==='active'?'success':state==='pending_approval'?'warning':'muted'}>{labels[state]??state}</Badge></div><p className="mt-2 text-sm text-muted">Kalkış: {formatDate(row.departure_date)}</p>{row.title&&<p className="mt-1 break-words text-sm">{row.title}</p>}</div><div className="flex flex-wrap gap-2">{['active','sold','expired'].includes(state)&&<Link className="rounded-lg border border-border px-3 py-3 text-sm" href={ROUTES.ilanlar.detail(row.slug||row.id)}>Görüntüle</Link>}{editable&&<Link className="rounded-lg border border-border px-3 py-3 text-sm" href={ROUTES.panel.editIlan(row.id)}>Düzenle</Link>}{state==='active'&&<Button variant="outline" disabled={!!busy} onClick={()=>action(row.id,'pause')}>Durdur</Button>}{editable&&<Button variant="outline" disabled={!!busy} onClick={()=>{if(window.confirm('İlan arşive alınacak ve aramada görünmeyecek. Devam edilsin mi?'))void action(row.id,'archive');}}>Arşivle</Button>}</div></article>;})}{visible?.length===0&&<div className="rounded-lg border border-border bg-surface p-10 text-center"><h2 className="font-semibold">{filter?'Bu durumda ilan bulunmuyor.':'Henüz ilan vermedin.'}</h2><p className="mt-2 text-sm text-muted">Yeni güzergâhını ücretsiz paylaşabilir, inceleme sonucunu buradan takip edebilirsin.</p></div>}</div>}</div>;
}
