import type {ArticleContent} from './content.type';
const publishedAt='2026-03-30T09:00:00.000Z';
const updatedAt='2026-09-09T01:00:00.000Z';
export const BLOG_POSTS:ArticleContent[]=[
 {slug:'p2p-kargo-nedir',seoKey:'blog_p2p_kargo_nedir',eyebrow:'Rehber',title:'P2P kargo nedir?',summary:'Taşıyıcı güzergâhlarıyla gönderi sahiplerinin doğrudan buluşmasını sağlayan model.',description:'P2P kargo yaklaşımını ve PaketJet üzerinden taşıyıcı iletişimine nasıl erişildiğini öğren.',publishedAt,updatedAt,categoryLabel:'Ürün rehberi',canonicalPath:'/blog/p2p-kargo-nedir',sections:[
  {title:'Güzergâhını paylaşan taşıyıcı, uygun ilanı arayan gönderici',paragraphs:['PaketJet’te taşıyıcılar çıkış ve varış şehirlerini, hareket tarihini, araç tipini ve güzergâh açıklamasını ilan olarak paylaşır. Gönderi sahipleri bu ilanları inceleyerek ihtiyaçlarına uygun taşıyıcıları bulabilir.','İlan vermek ücretsizdir. İletişim bilgileri kamuya açık listede gösterilmez. Gönderici, bir ilan alma hakkı kullanarak veya kartla ödeme açıksa tekil iletişim alımı yaparak taşıyıcının bilgilerine erişir.']},
  {title:'Ödenen ücret ne içindir?',paragraphs:['PaketJet üzerinden alınan hizmet, ilanın iletişim bilgilerine erişimdir. Bu ücret taşıma bedeli değildir. Gönderinin kabulü, taşıma ücreti, teslim noktaları ve zamanlamayı gönderici ile taşıyıcı doğrudan görüşerek belirler.','PaketJet üzerinden taşıma rezervasyonu, paket takibi, emanet ödeme veya taşıyıcıya ödeme aktarımı yapılmaz. İletişim erişimi, gönderinin taşınacağını ya da teslim edileceğini garanti etmez.']},
  {title:'İlanı seçmeden önce',paragraphs:['Kalkış tarihini ve güzergâhı kontrol et. Gönderinin türünü, boyutlarını ve özel ihtiyaçlarını açıkça tarif etmeye hazır ol. İletişimi açmadan önce gönderi değeri ve içerik beyanını doğru doldur; taşıma kurallarını oku.','İletişim açıldıktan sonra kayıt Satın aldıklarım ekranında saklanır. İlanın süresi dolsa da kazandığın iletişim erişimi için yeniden hak harcaman gerekmez.']},
 ]},
 {slug:'paketjet-nasil-kullanilir',seoKey:'blog_paketjet_nasil_kullanilir',eyebrow:'Rehber',title:'PaketJet nasıl kullanılır?',summary:'İlan arama, iletişim açma ve ücretsiz güzergâh paylaşımı için kullanım rehberi.',description:'Gönderici ve taşıyıcı için PaketJet’in temel adımlarını öğren.',publishedAt,updatedAt,categoryLabel:'Kullanım rehberi',canonicalPath:'/blog/paketjet-nasil-kullanilir',sections:[
  {title:'1. Güncel güzergâhları ara',paragraphs:['İlanlar sayfasında çıkış ve varış adresini, ardından tarihi seç. Köy, mahalle veya açık adres yazabilir, harita destekli önerilerden seçim yapabilirsin. Gerekiyorsa araç tipine göre filtrele. Arama sonuçları yalnız hareket zamanı geçmemiş, yayında olan ilanları gösterir.','Tam adreste uygun ilan yoksa aynı ildeki ilanlar, tarih ve araç tercihin korunarak alternatif olarak gösterilebilir. Alternatiflerin kesin buluşma noktasını taşıyıcıyla görüş. Bir rotada ilan bulunması veya düzenli sefer yapılması garanti değildir.']},
  {title:'2. İlanı ve erişim koşullarını incele',paragraphs:['İlanın açıklamasını ve hareket saatini oku. Giriş yaptıktan sonra erişim fiyatını ve mevcut haklarını görebilirsin. İletişimi açmak için gerekli gönderi değeri ve içerik beyanını tamamla.','Hakla alım başarılı olunca bir hak düşer. Kartla alımda sonuç, sunucunun doğruladığı ödeme kaydından gelir. Ekranı kapatmak bir ödemeyi iptal etmez; bekleyen veya incelemeye alınmış işlemde tekrar ödeme yapmadan durumu kontrol et.']},
  {title:'3. Taşıyıcıyla doğrudan görüş',paragraphs:['Açılan telefon veya e-posta bilgisiyle taşıyıcıya ulaş. Gönderi içeriğini ve ölçülerini, teslim noktalarını, zamanlamayı ve taşıma bedelini birlikte netleştir. PaketJet’in iletişim erişim bedeli, bu taşıma bedelinden ayrıdır.','Satın aldıklarım ekranından iletişime yeniden dönebilirsin. Ödeme veya erişim sorunu varsa işlem referansını destek talebine ekle; kart bilgisi veya parola paylaşma.']},
  {title:'Taşıyıcı olarak ücretsiz ilan ver',paragraphs:['Ücretsiz ilan ver düğmesini seç. Rota ve tarihleri, araç bilgilerini, açıklamanı ve özel iletişim alanlarını doldur. Önizlemeyi kontrol edip incelemeye gönder.','İncelemeye gönderilen ilan hemen yayında sayılmaz. Durumunu İlanlarım ekranından takip edebilir, uygun ilanları düzenleyebilir veya durdurabilirsin. Düzenlenen ilan tekrar incelemeye alınır; satılmış ilan yeniden satışa açılmaz.']},
 ]},
];
export const ROUTE_GUIDES:ArticleContent[]=[['istanbul-ankara','İstanbul','Ankara'],['istanbul-izmir','İstanbul','İzmir']].map(([slug,from,to])=>({
 slug,seoKey:`rota_${slug.replaceAll('-','_')}`,eyebrow:'Güzergâh rehberi',title:`${from} – ${to}`,summary:`${from} ile ${to} arasındaki taşıyıcı ilanlarını değerlendirirken dikkat edilecekler.`,description:`${from} – ${to} güzergâhında güncel ilan arama ve taşıyıcıyla doğrudan iletişim rehberi.`,publishedAt,updatedAt,categoryLabel:'Güzergâh',canonicalPath:`/rota/${slug}`,sections:[
  {title:'Güncel ilanları kontrol et',paragraphs:[`${from} çıkışlı ve ${to} varışlı ilanları arama ekranında filtreleyebilirsin. Kalkış tarihini kontrol et; bu rehber rotada sürekli veya belirli sayıda ilan bulunduğu anlamına gelmez.`,'Şehir bilgisi tek başına teslim noktasını belirlemez. İlçe, buluşma noktası ve taşıyıcının rotadan sapıp sapamayacağı gibi ayrıntıları doğrudan görüşmede netleştir.']},
  {title:'Gönderini açıkça tarif et',paragraphs:['Gönderinin içeriği, ölçüsü, ağırlığı ve paketleme durumu taşıyıcının kabul kararını etkileyebilir. İlan açıklamasını oku ve taşıyıcıyla görüşürken bu bilgileri paylaş. Taşıma kurallarındaki sınırlamaları dikkate al.']},
  {title:'İletişim bedeli ile taşıma bedeli ayrıdır',paragraphs:['PaketJet’te satın aldığın şey ilanın iletişim bilgilerine erişimdir. Taşıma ücreti ve teslim koşulları gönderici ile taşıyıcı arasında belirlenir. Platform üzerinden taşıma rezervasyonu veya teslim garantisi verilmez.']},
 ]
}));
export const getBlogPostBySlug=(slug:string)=>BLOG_POSTS.find(post=>post.slug===slug);
export const getRouteGuideBySlug=(slug:string)=>ROUTE_GUIDES.find(post=>post.slug===slug);
